[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.26'
evm_version = 'cancun'
fuzz = { runs = 256 }
invariant = { runs = 256, fail_on_revert = true }
remappings = [
    'forge-std/=lib/forge-std/src/',
    'v4-core/=lib/v4-core/contracts/',
    'v4-periphery/=lib/v4-periphery/contracts/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/'
]

# Profile for testing without fork
[profile.local]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.26'
evm_version = 'cancun'
fuzz = { runs = 256 }
invariant = { runs = 256 }
# No fork URL

# Profile for testing with Base Sepolia
[profile.sepolia]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.26'
evm_version = 'cancun'
fuzz = { runs = 256 }
invariant = { runs = 256 }
fork_url = "https://sepolia.base.org"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" } 